apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: firstspringboot
  name: firstspringboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstspringboot
  strategy: {}
  template:
    metadata:
      labels:
        app: firstspringboot
    spec:
      containers:
      - image: saikat17ster/firstspringboot:v1
        name: firstspringboot
        resources: {}
        ports:
          - containerPort: 8080
status: {}
